# Generated by Django 5.1.5 on 2025-04-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentcity',
            old_name='сreated_at',
            new_name='created_at',
        ),
    ]
